### ISSUE TITLE
Package activitystream shouldn depend on redis

### ISSUE THREAD

**Issue by emersion** [chrisport/go-activitystream#1]
Package activitystream shouldn't depend on redis. The only place is see that redis is used is here: https://github.com/chrisport/go-activitystream/blob/master/activitystream/interface.go#L29

Instead, the package can define this error itself and check if `err == redis.ErrNil || err == activitystream.ErrEmpty`.

That would allow to use the package without using redis.

**Comment by chrisport** [comment]
thanks, I removed it
